apiVersion: v1
kind: ReplicationController
metadata:
  name: php
spec:
  replicas: 1
  selector:
    app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: sugare/php7-fpm-pdo
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: php-www
          mountPath: /var/www/html
      volumes:
      - name: php-www
        hostPath:
          path: /home/ubuntu/song/www
