apiVersion: v1
kind: ReplicationController
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-html
        hostPath:  
          path: /home/ubuntu/KubeApp/haproxy/app1
