apiVersion: v1
kind: ReplicationController
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: nginx:latest
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: nginx-html
        hostPath:
          path: /home/ubuntu/KubeApp/haproxy/app2
