version: '3'
services:
  app1: 
    image: nginx:latest
    container_name: app1
    volumes:
    - /home/ubuntu/haproxy/app1:/usr/share/nginx/html

  app2:
    image: nginx:latest
    container_name: app2
    volumes:
    - /home/ubuntu/haproxy/app2:/usr/share/nginx/html

  haproxy:
    image: haproxy:1.7
    container_name: app
    ports:
    - "80:80"
    volumes:
    - /home/ubuntu/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
    - app1
    - app2
